#!/usr/bin/env bash
set -x
HERE=$(dirname $0)

. $HERE/common

docker rm -f \
    $REDIS \
    $SERVER \
    $WORKER \
    $DEBUG

docker network rm $NETWORK || true

docker volume rm $ORDERLY_VOLUME || true
docker volume rm $LIBRARY_VOLUME || true

rm -rf $HERE/test-repo
rm -rf $HERE/orderly-root-volume
