#!/usr/bin/env bash
set -x
HERE=$(dirname $0)

docker kill \
    orderly.runner_redis \
    orderly.runner_server \
    orderly.runner_worker \
    orderly.runner_debug

docker rm \
    orderly.runner_redis \
    orderly.runner_server \
    orderly.runner_worker \
    orderly.runner_debug

docker network rm orderly.runner_network

docker volume rm orderly-root-volume

rm -rf $HERE/test-repo
rm -rf $HERE/orderly-root-volume
