#!/usr/bin/env bash
set -exu
HERE=$(dirname $0)
ABSOLUTE_PATH=$(realpath $HERE)

. $HERE/common

$HERE/setup-test-repo

docker network create $NETWORK

docker run --rm -d \
       --net=$NETWORK \
       --name=$REDIS \
       -p 127.0.0.1:6379:6379 \
       redis

docker volume create $ORDERLY_VOLUME
docker volume create $ORDERLY_LOGS_VOLUME

docker run --rm -d --pull=missing \
       --name=$DEBUG \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       -v $ORDERLY_LOGS_VOLUME:$LOGS_DIR \
       ubuntu \
       sleep infinity

docker cp $ABSOLUTE_PATH/test-repo/. $DEBUG:$CONTAINER_ORDERLY_ROOT_PATH

docker run --rm -d --pull=always \
       --net=$NETWORK \
       --name=$SERVER \
       --entrypoint="/usr/local/bin/orderly.runner.server" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_URL=redis://$REDIS \
       -p 127.0.0.1:8001:8001 \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       -v $ORDERLY_LOGS_VOLUME:$LOGS_DIR \
       $ORDERLY_RUNNER_IMAGE \
       $CONTAINER_ORDERLY_ROOT_PATH \
       /repositories

docker run --rm -d --pull=always \
       --net=$NETWORK \
       --name=$WORKER \
       --entrypoint="/usr/local/bin/orderly.runner.worker" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_URL=redis://$REDIS \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       -v $ORDERLY_LOGS_VOLUME:$LOGS_DIR \
       $ORDERLY_RUNNER_IMAGE \
       $CONTAINER_ORDERLY_ROOT_PATH
