#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
ABSOLUTE_PATH=$(realpath $HERE)

$HERE/setup-test-repo

docker network create orderly.runner_network

docker run --rm -d \
       --net=orderly.runner_network \
       --name=orderly.runner_redis \
       -p 127.0.0.1:6379:6379 \
       redis

docker run --rm -d --pull=always \
       --net=orderly.runner_network \
       --name=orderly.runner_server \
       --entrypoint="/usr/local/bin/orderly.runner.server" \
       -p 127.0.0.1:8001:8001 \
       -v $ABSOLUTE_PATH/test-repo:/orderly-root \
       ghcr.io/mrc-ide/orderly.runner:mrc-5146-container-gh-actions \
       /orderly-root

docker run --rm -d --pull=always \
       --net=orderly.runner_network \
       --name=orderly.runner_worker \
       --entrypoint="/usr/local/bin/orderly.runner.worker" \
       -v $ABSOLUTE_PATH/test-repo:/orderly-root \
       ghcr.io/mrc-ide/orderly.runner:mrc-5146-container-gh-actions \
       /orderly-root
