#!/usr/bin/env bash
set -exu
HERE=$(dirname $0)
ABSOLUTE_PATH=$(realpath $HERE)

. $HERE/common

# --local flag allows you to build an image from local source and use that for the test run, instead of pulling from the registry.
PULL_POLICY=always
if [[ "${1:-}" == "--local" ]]; then
    docker build -t orderly.runner:local -f "$HERE/../Dockerfile" "$HERE/../.."
    ORDERLY_RUNNER_IMAGE=orderly.runner:local
    PULL_POLICY=missing # This local build won't be in the registry, so avoid attempting to pull
fi

$HERE/setup-test-repo

docker network create $NETWORK

docker run --rm -d \
       --net=$NETWORK \
       --name=$REDIS \
       -p 127.0.0.1:6379:6379 \
       redis

docker volume create $ORDERLY_VOLUME
docker volume create $ORDERLY_LOGS_VOLUME
docker volume create $LIBRARY_VOLUME

# Install a test package into the library volume,
# to be returned by the library_list API endpoint.
docker run --rm --pull=$PULL_POLICY \
       --volume=$LIBRARY_VOLUME:$LIBRARY_MOUNT_PATH \
       $ORDERLY_RUNNER_IMAGE \
       Rscript -e "install.packages('mime', lib='$LIBRARY_MOUNT_PATH')"

docker run --rm -d --pull=missing \
       --name=$DEBUG \
       --volume=$ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       --volume=$ORDERLY_LOGS_VOLUME:$LOGS_DIR \
       ubuntu \
       sleep infinity

docker cp $ABSOLUTE_PATH/test-repo/. $DEBUG:$CONTAINER_ORDERLY_ROOT_PATH

docker run --rm -d --pull=$PULL_POLICY \
       --net=$NETWORK \
       --name=$SERVER \
       --entrypoint="/usr/local/bin/orderly.runner.server" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_URL=redis://$REDIS \
       -p 127.0.0.1:8001:8001 \
       --volume=$ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       --volume=$ORDERLY_LOGS_VOLUME:$LOGS_DIR \
       --volume=$LIBRARY_VOLUME:$LIBRARY_MOUNT_PATH \
       $ORDERLY_RUNNER_IMAGE \
       /repositories

docker run --rm -d --pull=$PULL_POLICY \
       --net=$NETWORK \
       --name=$WORKER \
       --entrypoint="/usr/local/bin/orderly.runner.worker" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_URL=redis://$REDIS \
       --volumes-from=$SERVER \
       $ORDERLY_RUNNER_IMAGE \
       $CONTAINER_ORDERLY_ROOT_PATH
