# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/",
        root,
        returning = porcelain::porcelain_returning_json("root"),
        validate = validate)
    },
    "POST /repository/fetch" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/repository/fetch",
        repository_fetch,
        porcelain::porcelain_input_query(url = "string"),
        porcelain::porcelain_input_body_json("data", "repository_fetch_request"),
        porcelain::porcelain_state(repositories_base_path = state$repositories_base_path),
        returning = porcelain::porcelain_returning_json("repository_fetch_response"),
        validate = validate)
    },
    "GET /repository/branches" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/repository/branches",
        repository_branches,
        porcelain::porcelain_input_query(url = "string"),
        porcelain::porcelain_state(repositories_base_path = state$repositories_base_path),
        returning = porcelain::porcelain_returning_json("repository_branches"),
        validate = validate)
    },
    "GET /report/list" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/report/list",
        report_list,
        porcelain::porcelain_input_query(url = "string", ref = "string"),
        porcelain::porcelain_state(repositories_base_path = state$repositories_base_path),
        returning = porcelain::porcelain_returning_json("report_list"),
        validate = validate)
    },
    "GET /report/parameters" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/report/parameters",
        report_parameters,
        porcelain::porcelain_input_query(url = "string", ref = "string", name = "string"),
        porcelain::porcelain_state(repositories_base_path = state$repositories_base_path),
        returning = porcelain::porcelain_returning_json("report_parameters"),
        validate = validate)
    },
    "POST /report/run" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/report/run",
        submit_report_run,
        porcelain::porcelain_input_query(url = "string"),
        porcelain::porcelain_input_body_json("data", "report_run_request"),
        porcelain::porcelain_state(queue = state$queue),
        returning = porcelain::porcelain_returning_json("report_run_response"),
        validate = validate)
    },
    "POST /report/status" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/report/status",
        report_run_status,
        porcelain::porcelain_input_query(include_logs = "logical"),
        porcelain::porcelain_input_body_json("data", "report_run_status_request"),
        porcelain::porcelain_state(queue = state$queue),
        returning = porcelain::porcelain_returning_json("report_run_status_response"),
        validate = validate)
    },
    "POST /report/cancel" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/report/cancel",
        report_run_cancel,
        porcelain::porcelain_input_body_json("data", "report_run_cancel_request"),
        porcelain::porcelain_state(queue = state$queue),
        returning = porcelain::porcelain_returning_json("report_run_cancel_response"),
        validate = validate)
    })
}
