# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/",
        root,
        returning = porcelain::porcelain_returning_json("root"),
        validate = validate)
    },
    "GET /report/list" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/report/list",
        report_list,
        porcelain::porcelain_input_query(ref = "string"),
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_json("report_list"),
        validate = validate)
    },
    "GET /report/<name:string>/parameters" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/report/<name:string>/parameters",
        report_parameters,
        porcelain::porcelain_input_query(ref = "string"),
        porcelain::porcelain_state(root = state$root),
        returning = porcelain::porcelain_returning_json("report_parameters"),
        validate = validate)
    },
    "POST /report/run" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "POST",
        "/report/run",
        submit_report_run,
        porcelain::porcelain_input_body_json("data", "report_run_request"),
        porcelain::porcelain_state(root = state$root, queue = state$queue),
        returning = porcelain::porcelain_returning_json("report_run_response"),
        validate = validate)
    },
    "GET /report/status/<job_id:string>" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/report/status/<job_id:string>",
        report_run_status,
        porcelain::porcelain_state(queue = state$queue),
        returning = porcelain::porcelain_returning_json("report_run_status_response"),
        validate = validate)
    })
}
